const competences = [
    { id: 'MATC1', description: 'Traduir un problema a una representació matemàtica i emprar conceptes, eines i estratègies matemàtiques per resoldre’l' },
    { id: 'MATC2', description: 'Donar i comprovar la solució d’un problema d’acord amb les preguntes plantejades' },
    { id: 'MATC3', description: 'Fer preguntes i generar problemes de caire matemàtic' },
    { id: 'MATC4', description: ' Fer conjectures matemàtiques adients en situacions quotidianes i comprovar-les' },
    { id: 'MATC5', description: 'Argumentar les afirmacions i els processos matemàtics realitzats en contextos propers' },
    { id: 'MATC6', description: 'Establir relacions entre diferents conceptes, així com entre els diversos significats d’un mateix concepte .' },
    { id: 'MATC7', description: 'Identificar les matemàtiques implicades en situacions quotidianes i escolars i cercar situacions que es puguin relacionar amb idees matemàtiques concretes' },
    { id: 'MATC8', description: 'Expressar idees i processos matemàtics de manera comprensible tot emprant el llenguatge verbal (oral i escrit)' },
    { id: 'MATC9', description: 'Usar les diverses representacions dels conceptes i relacions per expressar matemàticament una situació.' },
    { id: 'MATC10', description: 'Usar les eines tecnològiques amb criteri, de forma ajustada a la situació, i interpretar les representacions matemàtiques que ofereixen' },
    { id: 'LLENC1', description: 'Comprendre textos orals de la vida quotidiana, dels mitjans de comunicació i escolars' },
    { id: 'LLENC2', description: ' Produir textos orals de tipologia diversa adequats a la situació comunicativa' },
    { id: 'LLENC3', description: ' Interactuar oralment d’acord amb la situació comunicativa, utilitzant estratègies conversacionals' },
    { id: 'LLENC4', description: ' Llegir amb fluïdesa per comprendre textos de la vida quotidiana, dels mitjans de comunicació i escolars en diferents formats i suports' },
    { id: 'LLENC5', description: 'Aplicar estratègies de comprensió per obtenir informació, interpretar i valorar el contingut d’acord amb la tipologia i la complexitat del text i el propòsit de la lectura' },
    { id: 'LLENC6', description: 'Utilitzar, per comprendre un text, l’estructura i el format de cada gènere textual i el component semàntic de les paraules i de les estructures morfosintàctiques més habituals' },
    { id: 'LLENC7', description: 'Aplicar estratègies de cerca i gestió de la informació per adquirir coneixement propi' },
    { id: 'LLENC8', description: 'Planificar l’escrit d’acord amb la situació comunicativa i el destinatari' },
    { id: 'LLENC9', description: 'Produir textos de tipologies diverses amb un lèxic i estructura que s’adeqüin al tipus de text, a les intencions i al destinatari' },
    { id: 'LLENC10', description: 'Revisar el text per millorar-lo i tenir cura de la seva presentació formal en funció de la situació comunicativa' },
    { id: 'LLENC11', description: ' Llegir fragments i obres i conèixer alguns autors i autores significatius de la literatura catalana, castellana i universal' },
    { id: 'LLENC12', description: ' Crear textos amb recursos literaris per expressar sentiments, realitats i ficcions' },
    { id: 'LLENC13', description: ' Ser conscient de la pertinença a la comunitat lingüística i cultural catalana i mostrar interès per l’ús de la llengua catalana' },    { id: 'LLENC14', description: 'Conèixer i valorar la diversitat lingüística i cultural de Catalunya, de l’Estat espanyol, d’Europa i del món' },
    { id: 'ESTC1', description: 'Obtenir informació bàsica i comprendre textos orals, senzills o adaptats, de la vida quotidiana, dels mitjans de comunicació i de l’àmbit escolar' },
    { id: 'ESTC2', description: 'Planificar i produir textos orals breus i senzills adequats a la situació comunicativa' },
    { id: 'ESTC3', description: ' Emprar estratègies d’interacció oral d’acord amb la situació comunicativa per iniciar, mantenir i acabar el discurs' },
    { id: 'ESTC4', description: 'Aplicar estratègies per obtenir informació bàsica i comprendre textos escrits senzills o adaptats de la vida quotidiana, dels mitjans de comunicació i de l’àmbit escolar' },
    { id: 'ESTC5', description: 'Interpretar els trets visuals, discursius i lingüístics bàsics d’un text d’estructura clara per comprendre’l' },
    { id: 'ESTC6', description: ' Utilitzar eines de consulta per accedir a la comprensió de textos' },
    { id: 'ESTC7', description: 'Planificar textos senzills a partir de la identificació dels elements més rellevants de la situació comunicativa' },
    { id: 'ESTC8', description: 'Produir textos senzills amb adequació a la situació comunicativa i amb l’ajut de suports' },
    { id: 'ESTC9', description: 'Revisar el text per millorar-lo en funció de la situació comunicativa amb l’ajut de suports específics' },
    { id: 'ESTC10', description: 'Comprendre i valorar textos literaris senzills, adaptats o autèntics, adequats a l’edat' },
    { id: 'ESTC11', description: 'Reproduir oralment i reescriure textos literaris senzills per gaudir-ne i fomentar el gaudi dels altres' },
    { id: 'ESTC12', description: 'Utilitzar estratègies plurilingües per a la comunicació' },
    { id: 'MEDC1', description: 'Plantejar-se preguntes sobre el medi, utilitzar estratègies de cerca de dades i analitzar resultats per trobar respostes' },
    { id: 'MEDC2', description: ' Interpretar el present a partir de l’anàlisi dels canvis i continuïtats al llarg del temps, per comprendre la societat en què vivim' },
    { id: 'MEDC3', description: 'Interpretar l’espai a partir dels elements del territori i de les seves representacions per situar-s’hi i desplaçar-s’hi' },
    { id: 'MEDC4', description: 'Analitzar paisatges i ecosistemes tenint en compte els factors socials i naturals que els configuren, per valorar les actuacions que els afecten' },
    { id: 'MEDC5', description: 'Valorar problemes socials rellevants interpretant-ne les causes i les conseqüències per plantejar propostes de futur' },
    { id: 'MEDC6', description: ' Adoptar hàbits sobre alimentació, activitat física i descans amb coneixements científics, per aconseguir el benestar físic' },
    { id: 'MEDC7', description: 'Prendre consciència del propi cos, de les emocions i sentiments propis i aliens, per aconseguir l’equilibri emocional i afavorir la convivència' },
    { id: 'MEDC8', description: ' Prendre decisions sobre higiene i salut amb coneixements científics per a la prevenció i guariment de malalties' },
    { id: 'MEDC9', description: 'Utilitzar materials de manera eficient amb coneixements científics i criteris tecnològics, per resoldre situacions quotidianes' },
    { id: 'MEDC10', description: 'Dissenyar màquines simples i utilitzar aparells de la vida quotidiana de forma segura i eficient' },
    { id: 'MEDC11', description: 'Adoptar hàbits sobre l’adquisició i ús de béns i serveis, amb coneixements científics i socials per esdevenir un consumidor responsable' },
    { id: 'MEDC12', description: 'Participar en la vida col·lectiva a partir de valors democràtics, per millorar la convivència i per afavorir un entorn més just i solidari' },
    { id: 'MEDC13', description: 'Valorar el sistema democràtic partint del coneixement dels sistemes polítics per esdevenir futurs ciutadans crítics' },
    { id: 'ARTC1', description: 'Mostrar hàbits de percepció conscient de la realitat visual i sonora de l’entorn natural i cultural' },
    { id: 'ARTC2', description: 'Utilitzar elements bàsics dels llenguatges visual, corporal i musical i estratègies per comprendre i apreciar les produccions artístiques' },
    { id: 'ARTC3', description: 'Comprendre i valorar elements significatius del patrimoni artístic proper, de Catalunya i d’arreu' },
    { id: 'ARTC4', description: 'Comprendre i valorar elements significatius de la contemporaneïtat artística' },
    { id: 'ARTC5', description: 'Emprar elements bàsics del llenguatge visual amb tècniques i eines artístiques per expressar-se i comunicar-se' },
    { id: 'ARTC6', description: 'Interpretar música vocal i instrumental amb els elements i recursos bàsics del llenguatge musical' },
    { id: 'ARTC7', description: 'Emprar els elements i recursos bàsics del llenguatge escènic per expressar-se, interpretar i comunicar-se' },
    { id: 'ARTC8', description: 'Improvisar i crear amb els elements i recursos bàsics dels diferents llenguatges artístics' },
    { id: 'ARTC9', description: 'Dissenyar i realitzar projectes i produccions artístiques multidisciplinàries' },
    { id: 'EFIC1', description: 'Resoldre situacions motrius de forma eficaç en la pràctica d’activitats físiques' },
    { id: 'EFIC2', description: 'Prendre consciència dels límits i les possibilitats del propi cos en la realització d’activitats físiques' },
    { id: 'EFIC3', description: 'Mostrar hàbits saludables en la pràctica d`activitats físiques i en la vida quotidiana' },
    { id: 'EFIC4', description: 'Valorar la pràctica habitual de l’activitat física com a factor beneficiós per a la salut' },
    { id: 'EFIC5', description: 'Comunicar vivències, emocions i idees utilitzant els recursos expressius del propi cos' },
    { id: 'EFIC6', description: 'Prendre part en activitats col·lectives d`expressió i comunicació corporal per afavorir la relació amb els altres' },
    { id: 'EFIC7', description: 'Participar en el joc col·lectiu de manera activa mostrant-se respectuós amb les normes i els companys' },
    { id: 'EFIC8', description: 'Practicar activitat física vinculada a l`entorn com una forma d`ocupació del temps de lleure' },
    { id: 'DIGC1', description: 'Seleccionar, utilitzar i programar dispositius digitals i les seves funcionalitats d’acord amb les tasques a realitzar' },
    { id: 'DIGC2', description: 'Utilitzar les funcions bàsiques de les aplicacions d’edició de textos, tractament de dades numèriques i presentacions multimèdia' },
    { id: 'DIGC3', description: 'Utilitzar programes i aplicacions de creació de dibuix i edició d’imatge fixa, so i imatge en moviment' },
    { id: 'DIGC4', description: 'Cercar, contrastar i seleccionar informació digital tot considerant diverses fonts i entorns digitals' },
    { id: 'DIGC5', description: 'Construir nou coneixement personal mitjançant estratègies de tractament de la informació amb el suport d’aplicacions digitals' },
    { id: 'DIGC6', description: 'Organitzar i emprar els propis entorns personals digitals de treball i d’aprenentatge' },
    { id: 'DIGC7', description: 'Realitzar comunicacions interpersonals virtuals i publicacions digitals' },
    { id: 'DIGC8', description: 'Realitzar activitats en grup utilitzant eines i entorns virtuals de treball col·laboratiu' },
    { id: 'DIGC9', description: ' Desenvolupar hàbits d’ús saludable de la tecnologia' },
    { id: 'DIGC10', description: ' Actuar de forma crítica, prudent i responsable en l’ús de les TIC, considerant aspectes ètics, legals, de seguretat, de sostenibilitat i d’identitat digital' },
    { id: 'APDC1', description: 'Prendre consciència de les característiques personals respecte de l’aprenentatge' },
    { id: 'APDC2', description: 'Ser conscient del que se sap i del que cal aprendre' },
    { id: 'APDC3', description: 'Organitzar el propi procés d’aprenentatge i aplicar-hi les tècniques adients' },
    { id: 'APDC4', description: ' Emprar tècniques de consolidació i recuperació dels aprenentatges' },
    { id: 'APDC5', description: 'Utilitzar la interacció i les tècniques d’aprenentatge en grup' },
    { id: 'APDC6', description: 'Adquirir el gust per aprendre i continuar aprenent' },
]

export { competences }